apiVersion: apps/v1
kind: Deployment
metadata:
  name: summarizer-agent
  namespace: agensys-demo-1
  labels:
    app: summarizer-agent
    component: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summarizer-agent
  template:
    metadata:
      labels:
        app: summarizer-agent
        component: agent
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: summarizer-agent
        image: ghcr.io/mirantis/agensys-codereview-demo/summarizer-agent:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: summarizer-config
        - secretRef:
            name: api-secrets
      restartPolicy: Always
